development:
  adapter: postgresql
  encoding: utf8
  database: recco_development
  pool: 5
  timeout: 5000
test:
  adapter: recco_test
  encoding: utf8
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: d2ieomvbbdbr8k
  username: byaaeghjbkyfzy
  password: JGi5HYNaWh0H9SRfxPcZWG32MO
  port: 5432
  pool: 5
  timeout: 5000
